MyDegree/Models/Student.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyDegree.Models {
  public class Student {
    [DatabaseGenerated (DatabaseGeneratedOption.None)]
    public int StudentId { get; set; }

    [Required]
    [Display (Name = "Given Name")]
    [StringLength (50, ErrorMessage = "Given name cannot be longer than 50 characters.")]
    public string GivenName { get; set; }

    [Display (Name = "Family Name")]
    [StringLength (50, ErrorMessage = "Family name cannot be longer than 50 characters.")]
    public string FamilyName { get; set; }

    [Display (Name = "Full Name")]
    public string FullName {
      get {
        return GivenName + " " + FamilyName;
      }
    }

    // Add navigation property for each related entity

    // each student has many plans... 
    public ICollection<StudentDegreePlan> StudentDegreePlans { get; set; }

    public override string ToString () {
      return base.ToString () + ": " +
        "StudentId = " + StudentId +
        "GivenName = " + GivenName +
        ", FamilyName = " + FamilyName +
        ", FullName = " + FullName +
        "";
    }
  }
}

MyDegree/Controllers/StudentDegreePlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyDegree.Data;
using MyDegree.Models;

namespace MyDegree.Controllers
{
    public class StudentDegreePlansController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentDegreePlansController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: StudentDegreePlans
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.StudentDegreePlans.Include(s => s.Degree).Include(s => s.DegreeStatus).Include(s => s.Student);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: StudentDegreePlans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentDegreePlan = await _context.StudentDegreePlans
                .Include(s => s.Degree)
                .Include(s => s.DegreeStatus)
                .Include(s => s.Student)
                .SingleOrDefaultAsync(m => m.StudentDegreePlanId == id);
            if (studentDegreePlan == null)
            {
                return NotFound();
            }

            return View(studentDegreePlan);
        }

        // GET: StudentDegreePlans/Create
        public IActionResult Create()
        {
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbrev");
            ViewData["DegreeStatusId"] = new SelectList(_context.DegreeStatuses, "DegreeStatusId", "Status");
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "GivenName");
            return View();
        }

        // POST: StudentDegreePlans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentDegreePlanId,StudentId,DegreeId,PlanNumber,PlanAbbrev,PlanName,DegreeStatusId,IncludesInternship")] StudentDegreePlan studentDegreePlan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentDegreePlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbrev", studentDegreePlan.DegreeId);
            ViewData["DegreeStatusId"] = new SelectList(_context.DegreeStatuses, "DegreeStatusId", "Status", studentDegreePlan.DegreeStatusId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "GivenName", studentDegreePlan.StudentId);
            return View(studentDegreePlan);
        }

        // GET: StudentDegreePlans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentDegreePlan = await _context.StudentDegreePlans.SingleOrDefaultAsync(m => m.StudentDegreePlanId == id);
            if (studentDegreePlan == null)
            {
                return NotFound();
            }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbrev", studentDegreePlan.DegreeId);
            ViewData["DegreeStatusId"] = new SelectList(_context.DegreeStatuses, "DegreeStatusId", "Status", studentDegreePlan.DegreeStatusId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "GivenName", studentDegreePlan.StudentId);
            return View(studentDegreePlan);
        }

        // POST: StudentDegreePlans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentDegreePlanId,StudentId,DegreeId,PlanNumber,PlanAbbrev,PlanName,DegreeStatusId,IncludesInternship")] StudentDegreePlan studentDegreePlan)
        {
            if (id != studentDegreePlan.StudentDegreePlanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentDegreePlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentDegreePlanExists(studentDegreePlan.StudentDegreePlanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DegreeId"] = new SelectList(_context.Degrees, "DegreeId", "DegreeAbbrev", studentDegreePlan.DegreeId);
            ViewData["DegreeStatusId"] = new SelectList(_context.DegreeStatuses, "DegreeStatusId", "Status", studentDegreePlan.DegreeStatusId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "GivenName", studentDegreePlan.StudentId);
            return View(studentDegreePlan);
        }

        // GET: StudentDegreePlans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentDegreePlan = await _context.StudentDegreePlans
                .Include(s => s.Degree)
                .Include(s => s.DegreeStatus)
                .Include(s => s.Student)
                .SingleOrDefaultAsync(m => m.StudentDegreePlanId == id);
            if (studentDegreePlan == null)
            {
                return NotFound();
            }

            return View(studentDegreePlan);
        }

        // POST: StudentDegreePlans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var studentDegreePlan = await _context.StudentDegreePlans.SingleOrDefaultAsync(m => m.StudentDegreePlanId == id);
            _context.StudentDegreePlans.Remove(studentDegreePlan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentDegreePlanExists(int id)
        {
            return _context.StudentDegreePlans.Any(e => e.StudentDegreePlanId == id);
        }
    }
}

MyDegree/Controllers/StudentsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDegree.Data;
using MyDegree.Models;

namespace MyDegree.Controllers {
  [Authorize]
  public class StudentsController : Controller {
    private readonly ApplicationDbContext _context;

    public StudentsController (ApplicationDbContext context) {
      _context = context;
    }

    // GET: Students
    public async Task<IActionResult> Index (string sortOrder, string searchString) {
      ViewData["FamilySortParam"] = String.IsNullOrEmpty (sortOrder) ? "family_desc" : "";
      ViewData["GivenSortParam"] = sortOrder == "given" ? "given_desc" : "given";
      ViewData["CurrentFilter"] = searchString;

      var students = from s in _context.Students
      select s;

      if (!String.IsNullOrEmpty (searchString)) {
        students = students.Where (s => s.FamilyName.Contains (searchString) ||
          s.GivenName.Contains (searchString));
      }

      switch (sortOrder) {
        case "family_desc":
          students = students.OrderByDescending (s => s.FamilyName);
          break;
        case "given_desc":
          students = students.OrderByDescending (s => s.GivenName);
          break;
        case "given":
          students = students.OrderBy (s => s.GivenName);
          break;
        default:
          students = students.OrderBy (s => s.FamilyName);
          break;
      }

      return View (await students.AsNoTracking().ToListAsync ());
    }

    // GET: Students/Details/5
    public async Task<IActionResult> Details (int? id) {
      if (id == null) {
        return NotFound ();
      }

      var student = await _context.Students
        .Include (d => d.StudentDegreePlans)
        .SingleOrDefaultAsync (m => m.StudentId == id);

      if (student == null) {
        return NotFound ();
      }

      return View (student);
    }

    // GET: Students/Create
    [Authorize]
    public IActionResult Create () {
      return View ();
    }

    // POST: Students/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create ([Bind ("StudentId,GivenName,FamilyName")] Student student) {
      if (ModelState.IsValid) {
        _context.Add (student);
        await _context.SaveChangesAsync ();
        return RedirectToAction (nameof (Index));
      }
      return View (student);
    }

    // GET: Students/Edit/5
    public async Task<IActionResult> Edit (int? id) {
      if (id == null) {
        return NotFound ();
      }

      var student = await _context.Students.SingleOrDefaultAsync (m => m.StudentId == id);
      if (student == null) {
        return NotFound ();
      }
      return View (student);
    }

    // POST: Students/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit (int id, [Bind ("StudentId,GivenName,FamilyName")] Student student) {
      if (id != student.StudentId) {
        return NotFound ();
      }

      if (ModelState.IsValid) {
        try {
          _context.Update (student);
          await _context.SaveChangesAsync ();
        } catch (DbUpdateConcurrencyException) {
          if (!StudentExists (student.StudentId)) {
            return NotFound ();
          } else {
            throw;
          }
        }
        return RedirectToAction (nameof (Index));
      }
      return View (student);
    }

    // GET: Students/Delete/5
    public async Task<IActionResult> Delete (int? id) {
      if (id == null) {
        return NotFound ();
      }
      var student = await _context.Students
        .SingleOrDefaultAsync (m => m.StudentId == id);
      if (student == null) {
        return NotFound ();
      }
      return View (student);
    }

    // POST: Students/Delete/5
    [HttpPost, ActionName ("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed (int id) {
      var student = await _context.Students.SingleOrDefaultAsync (m => m.StudentId == id);
      _context.Students.Remove (student);
      await _context.SaveChangesAsync ();
      return RedirectToAction (nameof (Index));
    }

    private bool StudentExists (int id) {
      return _context.Students.Any (e => e.StudentId == id);
    }
  }
}

MyDegree/Views/Students/Create.cshtml
@model MyDegree.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GivenName" class="control-label"></label>
                <input asp-for="GivenName" class="form-control" />
                <span asp-validation-for="GivenName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FamilyName" class="control-label"></label>
                <input asp-for="FamilyName" class="form-control" />
                <span asp-validation-for="FamilyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyDegree/Views/Students/Delete.cshtml
@model MyDegree.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GivenName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GivenName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FamilyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FamilyName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyDegree/Views/Students/Details.cshtml
@model MyDegree.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GivenName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GivenName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FamilyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FamilyName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.StudentDegreePlans)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Degree</th>
                    <th>Plan Number</th>
                    <th>Plan Abbrev</th>
                    <th>Plan Name</th>
                    <th>Degree Status</th>
                    <th>Includes Internship?</th>
                    <th>More</th>
                </tr>
                @foreach (var item in Model.StudentDegreePlans.OrderBy(p => p.PlanNumber))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreeId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlanNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlanAbbrev)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlanName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DegreeStatusId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IncludesInternship)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="StudentDegreePlans" asp-route-id="@item.StudentDegreePlanId">Plan</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StudentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyDegree/Views/Students/Edit.cshtml
@model MyDegree.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentId" />
            <div class="form-group">
                <label asp-for="GivenName" class="control-label"></label>
                <input asp-for="GivenName" class="form-control" />
                <span asp-validation-for="GivenName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FamilyName" class="control-label"></label>
                <input asp-for="FamilyName" class="form-control" />
                <span asp-validation-for="FamilyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyDegree/Views/Students/Index.cshtml
@model IEnumerable<MyDegree.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["GivenSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"> @Html.DisplayNameFor(model => model.GivenName)</a>
</th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["FamilySortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"> @Html.DisplayNameFor(model => model.FamilyName)</a>
</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GivenName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FamilyName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StudentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StudentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.StudentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>